# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_3rd_test1.ui'
#
# Created: Mon Oct 15 09:40:09 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 589)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.FWList = QtGui.QComboBox(self.centralwidget)
        self.FWList.setObjectName("FWList")
        self.gridLayout.addWidget(self.FWList, 2, 1, 1, 3)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 4, 1, 1)
        self.Get_Vdom = QtGui.QPushButton(self.centralwidget)
        self.Get_Vdom.setObjectName("Get_Vdom")
        self.gridLayout.addWidget(self.Get_Vdom, 2, 8, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.Pass = QtGui.QLineEdit(self.centralwidget)
        self.Pass.setObjectName("Pass")
        self.gridLayout.addWidget(self.Pass, 0, 5, 1, 1)
        self.Vdoms = QtGui.QComboBox(self.centralwidget)
        self.Vdoms.setObjectName("Vdoms")
        self.gridLayout.addWidget(self.Vdoms, 2, 5, 1, 1)
        self.FO = QtGui.QCheckBox(self.centralwidget)
        self.FO.setObjectName("FO")
        self.gridLayout.addWidget(self.FO, 0, 8, 1, 1)
        self.Username = QtGui.QLineEdit(self.centralwidget)
        self.Username.setObjectName("Username")
        self.gridLayout.addWidget(self.Username, 0, 1, 1, 3)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Output = QtGui.QTextEdit(self.tab_1)
        self.Output.setObjectName("Output")
        self.gridLayout_2.addWidget(self.Output, 3, 3, 6, 5)
        self.Diagnose_Stop = QtGui.QPushButton(self.tab_1)
        self.Diagnose_Stop.setObjectName("Diagnose_Stop")
        self.gridLayout_2.addWidget(self.Diagnose_Stop, 11, 4, 1, 1)
        self.Policy_Name = QtGui.QLineEdit(self.tab_1)
        self.Policy_Name.setObjectName("Policy_Name")
        self.gridLayout_2.addWidget(self.Policy_Name, 9, 4, 1, 1)
        self.Run = QtGui.QPushButton(self.tab_1)
        self.Run.setObjectName("Run")
        self.gridLayout_2.addWidget(self.Run, 10, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_1)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 3, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.tab_1)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 9, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Merge_1 = QtGui.QPushButton(self.tab_1)
        self.Merge_1.setObjectName("Merge_1")
        self.horizontalLayout.addWidget(self.Merge_1)
        self.Range_1 = QtGui.QPushButton(self.tab_1)
        self.Range_1.setObjectName("Range_1")
        self.horizontalLayout.addWidget(self.Range_1)
        self.Sort_1 = QtGui.QPushButton(self.tab_1)
        self.Sort_1.setObjectName("Sort_1")
        self.horizontalLayout.addWidget(self.Sort_1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 3)
        self.SRVSort = QtGui.QPushButton(self.tab_1)
        self.SRVSort.setObjectName("SRVSort")
        self.gridLayout_2.addWidget(self.SRVSort, 8, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Merge_2 = QtGui.QPushButton(self.tab_1)
        self.Merge_2.setObjectName("Merge_2")
        self.horizontalLayout_2.addWidget(self.Merge_2)
        self.Range_2 = QtGui.QPushButton(self.tab_1)
        self.Range_2.setObjectName("Range_2")
        self.horizontalLayout_2.addWidget(self.Range_2)
        self.Sort_2 = QtGui.QPushButton(self.tab_1)
        self.Sort_2.setObjectName("Sort_2")
        self.horizontalLayout_2.addWidget(self.Sort_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 7, 0, 1, 3)
        self.Apply = QtGui.QPushButton(self.tab_1)
        self.Apply.setObjectName("Apply")
        self.gridLayout_2.addWidget(self.Apply, 9, 7, 1, 1)
        self.dst = QtGui.QPlainTextEdit(self.tab_1)
        self.dst.setObjectName("dst")
        self.gridLayout_2.addWidget(self.dst, 6, 0, 1, 3)
        self.Check = QtGui.QCheckBox(self.tab_1)
        self.Check.setObjectName("Check")
        self.gridLayout_2.addWidget(self.Check, 0, 0, 1, 1)
        self.Output_Reset = QtGui.QPushButton(self.tab_1)
        self.Output_Reset.setObjectName("Output_Reset")
        self.gridLayout_2.addWidget(self.Output_Reset, 11, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_1)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 8, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab_1)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.Diagnose = QtGui.QPushButton(self.tab_1)
        self.Diagnose.setObjectName("Diagnose")
        self.gridLayout_2.addWidget(self.Diagnose, 10, 7, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_1)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 1)
        self.srv = QtGui.QPlainTextEdit(self.tab_1)
        self.srv.setObjectName("srv")
        self.gridLayout_2.addWidget(self.srv, 9, 0, 3, 3)
        self.Include_Any = QtGui.QCheckBox(self.tab_1)
        self.Include_Any.setObjectName("Include_Any")
        self.gridLayout_2.addWidget(self.Include_Any, 0, 2, 1, 1)
        self.NAT = QtGui.QCheckBox(self.tab_1)
        self.NAT.setObjectName("NAT")
        self.gridLayout_2.addWidget(self.NAT, 0, 4, 1, 1)
        self.Reset = QtGui.QPushButton(self.tab_1)
        self.Reset.setObjectName("Reset")
        self.gridLayout_2.addWidget(self.Reset, 10, 3, 1, 1)
        self.src = QtGui.QPlainTextEdit(self.tab_1)
        self.src.setObjectName("src")
        self.gridLayout_2.addWidget(self.src, 3, 0, 1, 3)
        self.Use_Backup = QtGui.QCheckBox(self.tab_1)
        self.Use_Backup.setObjectName("Use_Backup")
        self.gridLayout_2.addWidget(self.Use_Backup, 0, 3, 1, 1)
        self.Backup = QtGui.QPushButton(self.tab_1)
        self.Backup.setObjectName("Backup")
        self.gridLayout_2.addWidget(self.Backup, 11, 7, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget = QtGui.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(10, 10, 201, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.address_cleanup = QtGui.QPushButton(self.widget)
        self.address_cleanup.setObjectName("address_cleanup")
        self.verticalLayout.addWidget(self.address_cleanup)
        self.Policy_cleanup = QtGui.QPushButton(self.widget)
        self.Policy_cleanup.setObjectName("Policy_cleanup")
        self.verticalLayout.addWidget(self.Policy_cleanup)
        self.pushButton_3 = QtGui.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.Unused_addresses_cleanup = QtGui.QPushButton(self.widget)
        self.Unused_addresses_cleanup.setObjectName("Unused_addresses_cleanup")
        self.verticalLayout.addWidget(self.Unused_addresses_cleanup)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 5, 0, 1, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAdd_New_Firewall = QtGui.QAction(MainWindow)
        self.actionAdd_New_Firewall.setObjectName("actionAdd_New_Firewall")
        self.actionSelect_All = QtGui.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionClear_Cash_Command = QtGui.QAction(MainWindow)
        self.actionClear_Cash_Command.setObjectName("actionClear_Cash_Command")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuTools.addAction(self.actionAdd_New_Firewall)
        self.menuTools.addAction(self.actionClear_Cash_Command)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.label_7.setBuddy(self.Vdoms)
        self.label_3.setBuddy(self.srv)
        self.label.setBuddy(self.src)
        self.label_2.setBuddy(self.dst)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.Reset, QtCore.SIGNAL("clicked()"), self.srv.clear)
        QtCore.QObject.connect(self.Reset, QtCore.SIGNAL("clicked()"), self.dst.clear)
        QtCore.QObject.connect(self.Reset, QtCore.SIGNAL("clicked()"), self.src.clear)
        QtCore.QObject.connect(self.Output_Reset, QtCore.SIGNAL("clicked()"), self.Output.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Username, self.Pass)
        MainWindow.setTabOrder(self.Pass, self.FO)
        MainWindow.setTabOrder(self.FO, self.FWList)
        MainWindow.setTabOrder(self.FWList, self.Vdoms)
        MainWindow.setTabOrder(self.Vdoms, self.Get_Vdom)
        MainWindow.setTabOrder(self.Get_Vdom, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.Check)
        MainWindow.setTabOrder(self.Check, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.Include_Any)
        MainWindow.setTabOrder(self.Include_Any, self.Use_Backup)
        MainWindow.setTabOrder(self.Use_Backup, self.NAT)
        MainWindow.setTabOrder(self.NAT, self.Merge_1)
        MainWindow.setTabOrder(self.Merge_1, self.Range_1)
        MainWindow.setTabOrder(self.Range_1, self.Sort_1)
        MainWindow.setTabOrder(self.Sort_1, self.Merge_2)
        MainWindow.setTabOrder(self.Merge_2, self.Range_2)
        MainWindow.setTabOrder(self.Range_2, self.Sort_2)
        MainWindow.setTabOrder(self.Sort_2, self.SRVSort)
        MainWindow.setTabOrder(self.SRVSort, self.Policy_Name)
        MainWindow.setTabOrder(self.Policy_Name, self.Apply)
        MainWindow.setTabOrder(self.Apply, self.Reset)
        MainWindow.setTabOrder(self.Reset, self.Run)
        MainWindow.setTabOrder(self.Run, self.Diagnose)
        MainWindow.setTabOrder(self.Diagnose, self.Output_Reset)
        MainWindow.setTabOrder(self.Output_Reset, self.Diagnose_Stop)
        MainWindow.setTabOrder(self.Diagnose_Stop, self.Backup)
        MainWindow.setTabOrder(self.Backup, self.src)
        MainWindow.setTabOrder(self.src, self.dst)
        MainWindow.setTabOrder(self.dst, self.srv)
        MainWindow.setTabOrder(self.srv, self.Output)
        MainWindow.setTabOrder(self.Output, self.address_cleanup)
        MainWindow.setTabOrder(self.address_cleanup, self.Policy_cleanup)
        MainWindow.setTabOrder(self.Policy_cleanup, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.Unused_addresses_cleanup)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "FG & SRX Firewalls Policy Manager                   Created By Thamer Mahmoud", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#aa0000;\">Firewall</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#aa0000;\">VDOM / RI:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Get_Vdom.setText(QtGui.QApplication.translate("MainWindow", "Get VDOM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#aa0000;\">Password:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.FO.setText(QtGui.QApplication.translate("MainWindow", "FO", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#aa0000;\">Username:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Diagnose_Stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.Run.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#aa0000;\">Output</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "QCheck", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#aa0000;\">Policy Name</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Merge_1.setText(QtGui.QApplication.translate("MainWindow", "Merge", None, QtGui.QApplication.UnicodeUTF8))
        self.Range_1.setText(QtGui.QApplication.translate("MainWindow", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.Sort_1.setText(QtGui.QApplication.translate("MainWindow", "Sort", None, QtGui.QApplication.UnicodeUTF8))
        self.SRVSort.setText(QtGui.QApplication.translate("MainWindow", "Service Sort", None, QtGui.QApplication.UnicodeUTF8))
        self.Merge_2.setText(QtGui.QApplication.translate("MainWindow", "Merge", None, QtGui.QApplication.UnicodeUTF8))
        self.Range_2.setText(QtGui.QApplication.translate("MainWindow", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.Sort_2.setText(QtGui.QApplication.translate("MainWindow", "Sort", None, QtGui.QApplication.UnicodeUTF8))
        self.Apply.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.Check.setText(QtGui.QApplication.translate("MainWindow", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.Output_Reset.setText(QtGui.QApplication.translate("MainWindow", "Output Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#aa0000;\">Service</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#aa0000;\">Sources</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Diagnose.setText(QtGui.QApplication.translate("MainWindow", "Diagnose", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#aa0000;\">Destination</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Include_Any.setText(QtGui.QApplication.translate("MainWindow", "Include Any", None, QtGui.QApplication.UnicodeUTF8))
        self.NAT.setText(QtGui.QApplication.translate("MainWindow", "NAT", None, QtGui.QApplication.UnicodeUTF8))
        self.Reset.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.Use_Backup.setText(QtGui.QApplication.translate("MainWindow", "Use Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.Backup.setText(QtGui.QApplication.translate("MainWindow", "Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.address_cleanup.setText(QtGui.QApplication.translate("MainWindow", "Duplicated Addresses Cleanup", None, QtGui.QApplication.UnicodeUTF8))
        self.Policy_cleanup.setText(QtGui.QApplication.translate("MainWindow", "Policy Cleanup", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.Unused_addresses_cleanup.setText(QtGui.QApplication.translate("MainWindow", "Unused Addresses Cleanup", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_New_Firewall.setText(QtGui.QApplication.translate("MainWindow", "Add New Firewall", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Cash_Command.setText(QtGui.QApplication.translate("MainWindow", "Clear Cashing Command", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
